# -*- coding: utf-8 -*-
"""CiPE_GenAI

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VirREvid5OAtxMq0C8wlw8jPOo16TuD9
"""

# Test 1 CiPE

pip install predictionguard

import os
import json

import predictionguard as pg

# Set your Prediction Guard token as an environmental variable.
os.environ["PREDICTIONGUARD_TOKEN"] = "*"

# Define our prompt.
messages = [
    {
        "role": "system",
        "content": "You are a helpful assistant. Your model is hosted by Prediction Guard, a leading AI company."
    },
    {
        "role": "user",
        "content": "Where can I access the LLMs in a safe and secure environment?"
    }
]

result = pg.Chat.create(
    model="Neural-Chat-7B",
    messages=messages
)

print(json.dumps(
    result,
    sort_keys=True,
    indent=4,
    separators=(',', ': ')
))
